/* oxlint-disable jest/expect-expect -- report-style spec that writes the sheet attribute audit */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, it } from 'vitest'

import { loadFixture, getSheetFixtureTargets, scanFixtureCases, transformFixtureToSheet } from '../../fixtureLoader.js'
import { auditSheetAttributes } from '../../sheetAttributeAudit.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPORT_PATH = resolve(
  __dirname,
  '../../../../../../fixtures/reports/sheet-attribute-audit.md',
)
const REPRO_COMMAND = 'pnpm --filter @zupfnoter/core exec vitest run src/testing/__tests__/sheet/attribute_audit.spec.ts'

function renderReport(): string {
  const lines: string[] = [
    '# Sheet Attribute Audit',
    '',
    `Auto-generated by \`${REPRO_COMMAND}\`.`,
    '',
    'This report lists legacy-relevant Sheet fields that are missing, mismatched, or only present in the TS export.',
    '',
  ]

  for (const testCase of scanFixtureCases().filter((fixture) => fixture.hasSheetFixture)) {
    const fixture = loadFixture(testCase)
    const targets = getSheetFixtureTargets(fixture)
    for (const target of targets) {
      const actual = transformFixtureToSheet(fixture, target.extractNr)
      const issues = auditSheetAttributes(actual, target.expected)

      lines.push(`## ${testCase.id} [extract ${target.extractNr}]`)
      lines.push('')
      if (issues.length === 0) {
        lines.push('No missing, mismatched, or extra legacy-relevant attributes.', '')
        continue
      }

      lines.push(`- Issues: ${issues.length}`)
      for (const issue of issues) {
        lines.push(`- ${issue.path}.${issue.field} (${issue.kind})`)
        lines.push(`  - expected: ${JSON.stringify(issue.expected)}`)
        lines.push(`  - actual: ${JSON.stringify(issue.actual)}`)
      }
      lines.push('')
    }
  }

  return `${lines.join('\n')}\n`
}

describe('sheet attribute audit', () => {
  it('writes the sheet attribute audit markdown', () => {
    mkdirSync(dirname(REPORT_PATH), { recursive: true })
    writeFileSync(REPORT_PATH, renderReport(), 'utf-8')
    console.log(`\n[sheet-attribute-audit] Markdown: ${REPORT_PATH}\n`)
  })
})
