/* oxlint-disable jest/expect-expect -- report-style spec that writes the song attribute audit */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, it } from 'vitest'

import { loadFixture, scanFixtureCases, transformFixtureToSong } from '../../fixtureLoader.js'
import { normalizeRawSongFixture } from '../../semanticMatch.js'
import { auditSongAttributes } from '../../songAttributeAudit.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPORT_PATH = resolve(
  __dirname,
  '../../../../../../fixtures/reports/song-attribute-audit.md',
)
const REPRO_COMMAND = 'pnpm --filter @zupfnoter/core exec vitest run src/testing/__tests__/song/attribute_audit.spec.ts'

function formatValue(value: unknown): string {
  return JSON.stringify(value)
}

function renderReport(): string {
  const lines: string[] = [
    '# Song Attribute Audit',
    '',
    `Auto-generated by \`${REPRO_COMMAND}\`.`,
    '',
    'This report lists legacy fields that are missing or value-mismatched in the current TS Song export.',
    '',
  ]

  for (const testCase of scanFixtureCases().filter((fixture) => fixture.hasSongFixture)) {
    const fixture = loadFixture(testCase)
    if (fixture.song === null) continue
    const actual = transformFixtureToSong(fixture)
    const expected = normalizeRawSongFixture(fixture.song)
    const issues = auditSongAttributes(actual, expected)

    lines.push(`## ${testCase.id}`)
    lines.push('')
    if (issues.length === 0) {
      lines.push('No missing or mismatched attributes.', '')
      continue
    }

    lines.push(`- Issues: ${issues.length}`)
    for (const issue of issues) {
      lines.push(`- ${issue.path} (${issue.kind})`)
      lines.push(`  - expected: ${formatValue(issue.expected)}`)
      lines.push(`  - actual: ${formatValue(issue.actual)}`)
    }
    lines.push('')
  }

  return `${lines.join('\n')}\n`
}

describe('song attribute audit', () => {
  it('writes the song attribute audit markdown', () => {
    mkdirSync(dirname(REPORT_PATH), { recursive: true })
    writeFileSync(REPORT_PATH, renderReport(), 'utf-8')
    console.log(`\n[song-attribute-audit] Markdown: ${REPORT_PATH}\n`)
  })
})
