/* oxlint-disable jest/expect-expect -- report-style spec that writes the SVG gap markdown report */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, it } from 'vitest'

import {
  getOutputSvgFixtureTargets,
  loadFixture,
  scanFixtureCases,
  transformFixtureToSvg,
} from '../../fixtureLoader.js'
import {
  compareSvgFixtures,
  formatInteractionDiff,
  formatPixelDiff,
  formatStructuralDiff,
  type SvgComparisonSummary,
} from '../../svgComparison.js'

const SVG_ARTIFACT_ROOT = resolve('/private/tmp/zupfnoter-svg-artifacts', 'output_svg')

const __dirname = dirname(fileURLToPath(import.meta.url))
const MARKDOWN_REPORT_PATH = resolve(
  __dirname,
  '../../../../../../fixtures/reports/svg-gap-report.md',
)

function collectSvgSummaries(): SvgComparisonSummary[] {
  const summaries: SvgComparisonSummary[] = []
  const testCases = scanFixtureCases()
    .filter((c) => c.hasOutputSvgFixture)
    .filter((c) => getOutputSvgFixtureTargets(loadFixture(c)).some((target) => target.extractNr === 0))
    .sort((left, right) => {
      if (left.id === '3015_reference_sheet') return -1
      if (right.id === '3015_reference_sheet') return 1
      return left.id.localeCompare(right.id)
    })

  for (const testCase of testCases) {
    const fixture = loadFixture(testCase)
    const target = getOutputSvgFixtureTargets(fixture).find((entry) => entry.extractNr === 0)
    if (target === undefined) continue
    let actualSvg: string
    try {
      actualSvg = transformFixtureToSvg(fixture, 0)
    } catch (error) {
      actualSvg = error instanceof Error ? error.message : String(error)
    }
    summaries.push(compareSvgFixtures({
      fixtureId: testCase.id,
      extractNr: 0,
      legacy: target.expected,
      ts: actualSvg,
      artifactDir: resolve(SVG_ARTIFACT_ROOT, testCase.id),
    }))
  }
  return summaries
}

function renderMarkdownReport(summaries: SvgComparisonSummary[]): string {
  const failing = summaries.filter((s) => !s.matches)
  const lines: string[] = [
    '# SVG Gap Report',
    '',
    'Auto-generated by `pnpm --filter @zupfnoter/core exec vitest run src/testing/__tests__/output_svg/gap_report.spec.ts`.',
    '',
    'Compares the focused `output.extract-0.svg` fixtures against the SVG produced by the current TypeScript pipeline, with `3015_reference_sheet` first.',
    '',
    '## Summary',
    '',
    `- Fixtures with SVG reference: ${summaries.length}`,
    `- Matching:                    ${summaries.length - failing.length}`,
    `- Diverging:                   ${failing.length}`,
    '',
    '## Fixtures',
    '',
  ]

  if (summaries.length === 0) {
    lines.push('No SVG fixtures found.', '')
    return `${lines.join('\n')}\n`
  }

  for (const summary of summaries) {
    const status = summary.matches ? '✅' : '❌'
    lines.push(`### ${status} ${summary.fixtureId} [extract ${summary.extractNr}]`)
    lines.push('')
    lines.push(`- Total opening tags: legacy ${summary.legacyTagTotal}, ts ${summary.tsTagTotal} (Δ ${summary.tsTagTotal - summary.legacyTagTotal})`)
    lines.push('')
    lines.push(...formatPixelDiff(summary.pixelDiff))
    lines.push('')
    lines.push(...formatStructuralDiff(summary.structuralDiff))
    lines.push('')
    lines.push(...formatInteractionDiff(summary.interactionDiff))
    lines.push('')
  }

  return `${lines.join('\n')}\n`
}

describe('SVG gap report', () => {
  it('writes the SVG gap markdown report', { timeout: 30000 }, () => {
    const summaries = collectSvgSummaries()
    mkdirSync(dirname(MARKDOWN_REPORT_PATH), { recursive: true })
    writeFileSync(MARKDOWN_REPORT_PATH, renderMarkdownReport(summaries), 'utf-8')

    const failing = summaries.filter((s) => !s.matches).length
    console.log(
      `\n[svg-gap-report] Fixtures: ${summaries.length}, diverging: ${failing}\nMarkdown: ${MARKDOWN_REPORT_PATH}\n`,
    )
  })
})
