/* oxlint-disable jest/expect-expect -- report-style spec that writes the SVG gap markdown report */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, it } from 'vitest'

import {
  getOutputSvgFixtureTargets,
  loadFixture,
  scanFixtureCases,
  transformFixtureToSvg,
} from '../../fixtureLoader.js'
import { summarizeSvgGap, type SvgGapSummary } from '../../svgGapAnalysis.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const MARKDOWN_REPORT_PATH = resolve(
  __dirname,
  '../../../../../../fixtures/reports/svg-gap-report.md',
)

function collectSvgSummaries(): SvgGapSummary[] {
  const summaries: SvgGapSummary[] = []
  for (const testCase of scanFixtureCases().filter((c) => c.hasOutputSvgFixture)) {
    const fixture = loadFixture(testCase)
    for (const target of getOutputSvgFixtureTargets(fixture)) {
      let actualSvg: string
      try {
        actualSvg = transformFixtureToSvg(fixture, target.extractNr)
      } catch (error) {
        summaries.push({
          fixtureId: testCase.id,
          extractNr: target.extractNr,
          legacyTagTotal: 0,
          tsTagTotal: 0,
          tagCountDiffs: [],
          firstMismatches: [
            { index: 0, legacy: 'render error', ts: error instanceof Error ? error.message : String(error) },
          ],
          matches: false,
        })
        continue
      }
      summaries.push(
        summarizeSvgGap({
          fixtureId: testCase.id,
          extractNr: target.extractNr,
          legacy: target.expected,
          ts: actualSvg,
        }),
      )
    }
  }
  return summaries
}

function renderTagCountTable(diffs: SvgGapSummary['tagCountDiffs']): string[] {
  if (diffs.length === 0) return ['  All tag-type counts match.']
  const lines = [
    '  | Tag | Legacy | TS | Δ |',
    '  |-----|--------|----|---|',
  ]
  for (const diff of diffs) {
    const deltaStr = diff.delta > 0 ? `+${diff.delta}` : `${diff.delta}`
    lines.push(`  | \`${diff.name}\` | ${diff.legacy} | ${diff.ts} | ${deltaStr} |`)
  }
  return lines
}

function renderFirstMismatches(mismatches: SvgGapSummary['firstMismatches']): string[] {
  if (mismatches.length === 0) return []
  const lines: string[] = ['', '  First positional mismatches:']
  for (const m of mismatches) {
    lines.push(`  - index ${m.index}`)
    lines.push(`    - legacy: \`${m.legacy ?? '(none)'}\``)
    lines.push(`    - ts:     \`${m.ts ?? '(none)'}\``)
  }
  return lines
}

function renderMarkdownReport(summaries: SvgGapSummary[]): string {
  const failing = summaries.filter((s) => !s.matches)
  const lines: string[] = [
    '# SVG Gap Report',
    '',
    'Auto-generated by `pnpm --filter @zupfnoter/core exec vitest run src/testing/__tests__/output_svg/gap_report.spec.ts`.',
    '',
    'Compares each fixture\'s legacy `output.extract-<nr>.svg` against the SVG produced by the current TypeScript pipeline.',
    '',
    '## Summary',
    '',
    `- Fixtures with SVG reference: ${summaries.length}`,
    `- Matching:                    ${summaries.length - failing.length}`,
    `- Diverging:                   ${failing.length}`,
    '',
    '## Fixtures',
    '',
  ]

  if (summaries.length === 0) {
    lines.push('No SVG fixtures found.', '')
    return `${lines.join('\n')}\n`
  }

  for (const summary of summaries) {
    const status = summary.matches ? '✅' : '❌'
    lines.push(`### ${status} ${summary.fixtureId} [extract ${summary.extractNr}]`)
    lines.push('')
    lines.push(`- Total opening tags: legacy ${summary.legacyTagTotal}, ts ${summary.tsTagTotal} (Δ ${summary.tsTagTotal - summary.legacyTagTotal})`)
    lines.push('')
    lines.push(...renderTagCountTable(summary.tagCountDiffs))
    lines.push(...renderFirstMismatches(summary.firstMismatches))
    lines.push('')
  }

  return `${lines.join('\n')}\n`
}

describe('SVG gap report', () => {
  it('writes the SVG gap markdown report', () => {
    const summaries = collectSvgSummaries()
    mkdirSync(dirname(MARKDOWN_REPORT_PATH), { recursive: true })
    writeFileSync(MARKDOWN_REPORT_PATH, renderMarkdownReport(summaries), 'utf-8')

    const failing = summaries.filter((s) => !s.matches).length
    console.log(
      `\n[svg-gap-report] Fixtures: ${summaries.length}, diverging: ${failing}\nMarkdown: ${MARKDOWN_REPORT_PATH}\n`,
    )
  })
})
