/**
 * Auto-generated by `pnpm test:gaps`.
 *
 * This file contains currently failing legacy-comparison cases that are not
 * yet covered by fixtures/openImplementations.ts.
 *
 * If the array is empty, no new unclassified failures were detected.
 */

export const OPEN_IMPLEMENTATIONS_TEMPLATE = 
[
  {
    "id": "song.246-horch-was-kommt-von-draussen-rein-unclassified",
    "stage": "song",
    "scope": "246_Horch-was-kommt-von-draussen-rein",
    "summary": "Unclassified song legacy comparison failure detected for 246_Horch-was-kommt-von-draussen-rein.",
    "refs": [
      "packages/core/src/AbcToSong.ts"
    ],
    "fixtures": [
      "246_Horch-was-kommt-von-draussen-rein"
    ],
    "prompt": "Investigate the song legacy comparison failure for fixture 246_Horch-was-kommt-von-draussen-rein. Reproduce with: pnpm --filter @zupfnoter/core exec vitest run src/testing/__tests__/song/legacy_comparison.spec.ts -t \"246_Horch-was-kommt-von-draussen-rein\" Implement legacy parity, then either attach this failure to an existing entry in fixtures/openImplementations.ts or promote the template entry if it is a genuinely new gap.",
    "mismatchSummary": "  voices[0].entities.length:\n    expected: 125\n    actual:   124\n  voices[1].entities.length:\n    expected: 125\n    actual:   124\n  voices[2].entities.length:\n    expected: 122\n    actual:   121"
  },
  {
    "id": "song.3015-reference-sheet-unclassified",
    "stage": "song",
    "scope": "3015_reference_sheet",
    "summary": "Unclassified song legacy comparison failure detected for 3015_reference_sheet.",
    "refs": [
      "packages/core/src/AbcToSong.ts"
    ],
    "fixtures": [
      "3015_reference_sheet"
    ],
    "prompt": "Investigate the song legacy comparison failure for fixture 3015_reference_sheet. Reproduce with: pnpm --filter @zupfnoter/core exec vitest run src/testing/__tests__/song/legacy_comparison.spec.ts -t \"3015_reference_sheet\" Implement legacy parity, then either attach this failure to an existing entry in fixtures/openImplementations.ts or promote the template entry if it is a genuinely new gap.",
    "mismatchSummary": "  voices[0].entities.length:\n    expected: 38\n    actual:   39\n  voices[1].entities.length:\n    expected: 38\n    actual:   39\n  voices[2].entities.length:\n    expected: 30\n    actual:   31"
  },
  {
    "id": "sheet.246-horch-was-kommt-von-draussen-rein-extract-0-unclassified",
    "stage": "sheet",
    "scope": "246_Horch-was-kommt-von-draussen-rein [extract 0]",
    "summary": "Unclassified sheet legacy comparison failure detected for 246_Horch-was-kommt-von-draussen-rein extract 0.",
    "refs": [
      "packages/core/src/HarpnotesLayout.ts"
    ],
    "fixtures": [
      "246_Horch-was-kommt-von-draussen-rein"
    ],
    "extracts": [
      0
    ],
    "prompt": "Investigate the sheet legacy comparison failure for fixture 246_Horch-was-kommt-von-draussen-rein extract 0. Reproduce with: pnpm --filter @zupfnoter/core exec vitest run src/testing/__tests__/sheet/legacy_comparison.spec.ts -t \"246_Horch-was-kommt-von-draussen-rein [extract 0]\" Implement legacy parity, then either attach this failure to an existing entry in fixtures/openImplementations.ts or promote the template entry if it is a genuinely new gap.",
    "mismatchSummary": "  children.length:\n    expected: 1290\n    actual:   1275"
  },
  {
    "id": "sheet.lyrics-extract-0-unclassified",
    "stage": "sheet",
    "scope": "lyrics [extract 0]",
    "summary": "Unclassified sheet legacy comparison failure detected for lyrics extract 0.",
    "refs": [
      "packages/core/src/HarpnotesLayout.ts"
    ],
    "fixtures": [
      "lyrics"
    ],
    "extracts": [
      0
    ],
    "prompt": "Investigate the sheet legacy comparison failure for fixture lyrics extract 0. Reproduce with: pnpm --filter @zupfnoter/core exec vitest run src/testing/__tests__/sheet/legacy_comparison.spec.ts -t \"lyrics [extract 0]\" Implement legacy parity, then either attach this failure to an existing entry in fixtures/openImplementations.ts or promote the template entry if it is a genuinely new gap.",
    "mismatchSummary": "  children.length:\n    expected: 20\n    actual:   24"
  }
] as const

