import type { Meta, StoryObj } from '@storybook/vue3-vite'

import { ZnPanel, ZnSplitPane } from '@zupfnoter/design-system'

const meta = { title: 'Design System/ZnSplitPane', component: ZnSplitPane, tags: ['autodocs'], parameters: { docs: { description: { component: 'Teilt einen verfügbaren Bereich in zwei unabhängig befüllbare Bereiche. `primarySize` ist ein Prozentwert und wird zwischen `minPrimarySize` und `maxPrimarySize` begrenzt. Der Parent bestimmt damit den verfügbaren Raum; die eingefügten Panels und Inhalte bestimmen nur innerhalb ihres Bereichs ihre natürliche Größe. Der Splitter ist per Maus, Touch und Tastatur bedienbar.' } } }, argTypes: { orientation: { control: 'select', options: ['horizontal', 'vertical'] }, primarySize: { control: { type: 'number', min: 10, max: 90 } }, minPrimarySize: { control: { type: 'number', min: 0, max: 90 } }, maxPrimarySize: { control: { type: 'number', min: 10, max: 100 } }, handleSize: { control: { type: 'number', min: 1, max: 32 } } } } satisfies Meta<typeof ZnSplitPane>
export default meta
type Story = StoryObj<typeof meta>

export const Horizontal: Story = { render: (args) => ({ components: { ZnPanel, ZnSplitPane }, setup: () => ({ args }), template: '<div style="height:18rem"><ZnSplitPane v-bind="args"><template #primary><ZnPanel title="Editor" fill-height="false"><p>ABC-Text</p></ZnPanel></template><template #secondary><ZnPanel title="Vorschau" fill-height="false"><p>SVG-Vorschau</p></ZnPanel></template></ZnSplitPane></div>' }), args: { orientation: 'horizontal', primarySize: 55 } }
export const Vertical: Story = { render: (args) => ({ components: { ZnPanel, ZnSplitPane }, setup: () => ({ args }), template: '<div style="height:24rem"><ZnSplitPane v-bind="args"><template #primary><ZnPanel title="Oben" fill-height="false"><p>Oberer Bereich</p></ZnPanel></template><template #secondary><ZnPanel title="Unten" fill-height="false"><p>Unterer Bereich</p></ZnPanel></template></ZnSplitPane></div>' }), args: { orientation: 'vertical', primarySize: 45 } }
