/**
 * Shared helpers for per-stage gap report specs (song, sheet).
 *
 * The SVG gap report uses its own structural diff via `svgGapAnalysis.ts`,
 * so this module only handles the registry-driven Song/Sheet flow:
 * compare fixtures, classify failures against `openImplementations.ts`,
 * and render a per-stage markdown report.
 */
import { formatMismatches, type MatchResult } from './semanticMatch.js'
import {
  coversDetectedFailure,
  type DetectedFailure,
  type OpenImplementation,
} from './openImplementations.js'

export interface DetectedFailureWithDetails extends DetectedFailure {
  mismatchSummary: string
  znId?: string
}

export function pushFailureIfNeeded(
  failures: DetectedFailureWithDetails[],
  failure: DetectedFailure,
  result: MatchResult,
  znId?: string,
): void {
  if (result.passed) return
  failures.push({
    ...failure,
    mismatchSummary: formatMismatches(result),
    znId,
  })
}

export function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export function classifyFailures(
  failures: DetectedFailureWithDetails[],
  knownEntries: OpenImplementation[],
): {
  covered: Array<{ failure: DetectedFailureWithDetails; entries: OpenImplementation[] }>
  uncovered: DetectedFailureWithDetails[]
} {
  const covered: Array<{ failure: DetectedFailureWithDetails; entries: OpenImplementation[] }> = []
  const uncovered: DetectedFailureWithDetails[] = []

  for (const failure of failures) {
    const entries = knownEntries.filter((entry) => coversDetectedFailure(entry, failure))
    if (entries.length > 0) {
      covered.push({ failure, entries })
    } else {
      uncovered.push(failure)
    }
  }

  return { covered, uncovered }
}

export function makeImplementationPrompt(failure: DetectedFailureWithDetails): string {
  const testSelector = failure.stage === 'song'
    ? `pnpm --filter @zupfnoter/core exec vitest run src/testing/__tests__/song/legacy_comparison.spec.ts -t "${failure.fixtureId}"`
    : `pnpm --filter @zupfnoter/core exec vitest run src/testing/__tests__/sheet/legacy_comparison.spec.ts -t "${failure.fixtureId} [extract ${failure.extractNr ?? 0}]"`

  return [
    `Investigate the ${failure.stage} legacy comparison failure for fixture ${failure.fixtureId}${failure.extractNr !== undefined ? ` extract ${failure.extractNr}` : ''}.`,
    `Reproduce with: ${testSelector}`,
    `Implement legacy parity, then either attach this failure to an existing entry in fixtures/openImplementations.ts or promote the template entry if it is a genuinely new gap.`,
  ].join(' ')
}

/**
 * Renders the markdown gap report for a single pipeline stage (song or sheet).
 */
export function renderStageReport(args: {
  stageTitle: string
  stageKey: 'song' | 'sheet'
  entries: OpenImplementation[]
  covered: Array<{ failure: DetectedFailureWithDetails; entries: OpenImplementation[] }>
  uncovered: DetectedFailureWithDetails[]
  reproCommand: string
}): string {
  const { stageTitle, entries, covered, uncovered, reproCommand } = args
  const lines: string[] = [
    `# ${stageTitle} Gap Report`,
    '',
    `Auto-generated by \`${reproCommand}\`.`,
    '',
    `This report is a regenerated worklist for fixture-driven legacy parity at the **${args.stageKey}** stage.`,
    'If a gap is really fixed, remove it from `fixtures/openImplementations.ts`.',
    '',
    '## Summary',
    '',
    `- Open implementations: ${entries.length}`,
    `- Known-covered failures: ${covered.length}`,
    `- New unclassified failures: ${uncovered.length}`,
    '',
    '## Open Gaps',
    '',
  ]

  if (entries.length === 0) {
    lines.push('No open gaps.', '')
  } else {
    for (const entry of entries) {
      const fixtures = entry.fixtures?.length ? entry.fixtures.join(', ') : '-'
      lines.push(`- [ ] ${entry.id}`)
      lines.push(`  - Fixtures: ${fixtures}`)
      if (entry.scope) lines.push(`  - Scope: ${entry.scope}`)
      lines.push(`  - Summary: ${entry.summary}`)
      if (entry.prompt?.trim()) lines.push(`  - Prompt: ${entry.prompt.trim()}`)
      if (entry.refs?.length) lines.push(`  - Refs: ${entry.refs.join(', ')}`)
      lines.push('')
    }
  }

  lines.push('## New Unclassified Failures', '')
  if (uncovered.length === 0) {
    lines.push('None.', '')
  } else {
    for (const failure of uncovered) {
      lines.push(
        `- [ ] ${failure.stage}.${slugify(failure.fixtureId)}${failure.extractNr !== undefined ? ` [extract ${failure.extractNr}]` : ''}`,
      )
      lines.push(`  - Fixture: ${failure.fixtureId}`)
      if (failure.extractNr !== undefined) {
        lines.push(`  - Extract: ${failure.extractNr}`)
      }
      if (failure.znId) {
        lines.push(`  - znId: ${failure.znId}`)
      }
      lines.push(`  - Prompt: ${makeImplementationPrompt(failure)}`)
      lines.push('  - Mismatch Summary:')
      for (const mismatchLine of failure.mismatchSummary.split('\n')) {
        lines.push(`    ${mismatchLine}`)
      }
      lines.push('')
    }
  }

  return `${lines.join('\n')}\n`
}
