/**
 * Auto-generated by `pnpm test:gaps`.
 *
 * This file contains currently failing legacy-comparison cases that are not
 * yet covered by packages/core/src/testing/openImplementations.ts.
 *
 * If the array is empty, no new unclassified failures were detected.
 */

export const OPEN_IMPLEMENTATIONS_TEMPLATE = 
[] as const

